### ISSUE TITLE
Automatic Mocking:  Cannot generate random value for schema with allOf

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#16]
this feature seems very doable since `allOf` schemas are usually just joining two or more separate objects into one object.

Wondering if there serious roadblocks/reasons to not try and implement this feature?

**Comment by Gi60s** [comment]
I believe what it came down to in this case is that I didn't take the time to implement the feature. I remember starting work on it and then deciding I could add it later.

I'm happy to take another crack at it. It should be doable. I'll keep you posted.

**Comment by Gi60s** [comment]
Just an update. Generating a random value for an allOf requires a merge of all schemas within the allOf.

In some cases this is pretty simple:

```yml
allOf:
  - type: integer
    minimum: 0
  - type: integer
    minimum: 10

------ Becomes ------
type: integer
minimum: 0
maximum: 10
```

In other cases it becomes complex, and is not easily resolved. The two object definitions below may exist independently and were joined via a `$ref`. Independently they are valid, but once joined they can lead to an impossible merge.

During the validation sequence this is easy to handle because the value is validated against all schemas one at a time. It's easy to know if one fails. For a merge this is a more complex operation and I'm still looking into what it would take for these to merge or to produce an error.

```yml
allOf:
  - type: object
    required:
      - a
    properties:
      a:
        type: string
  - type: object
    additionalProperties: false
    properties:
      b:
        type: string

------ Has a conflict because "a" is required by one an not allowed by the other
```
