### ISSUE TITLE
Enhancement : add an option to add custom DataTypeFormat(s) when requiring ?

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-middleware#22]
Hello,

I checked in the [documentation](https://byu-oit.github.io/openapi-enforcer-middleware/api#openapienforcermiddleware) and it seems there is no clean way to easily add custom DataTypeFormat(s) like explained in [openapi-enforcer](https://byu-oit.github.io/openapi-enforcer/api/components/schema#definedatatypeformat) in the middelware. 

As the common [dataTypeFormat](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypeFormat) are already [here](https://github.com/byu-oit/openapi-enforcer/blob/master/index.js#L151), I think it could be useful to offer an configuration option to add more dataTypeFormat.

For example, If I have the following query parameters : 

```yaml
      parameters:
        - in: query
          style: form
          name: settings
          explode: true
          schema:
              type: object
              properties:
                state:
                  type: string
                  enum: [default, validated, pending]
                  default: default
                  description: "Filter the tags by their validity. The default value ('default') stands for no filtering."
                onlySelected:
                  type: array
                  description: "If not empty, only consider the given tag categories ID(S). If empty, no tag category is ignored"
                  default: []
                  uniqueItems: true
                  items:
                    type: integer
                    minimum: 0
                    example: 42
                    description: "A Tag Category ID"
``` 

In this case, it is useful to add a custom dataTypeFormat to deserialize a complex extracted parameter (`onlySelected`) into its right type ( here an array of integers) if possible. ( as query parsers like [querystring](https://nodejs.org/api/querystring.html) or [qs](https://www.npmjs.com/package/qs) can't do everything we want and by default keep values in string format )

```
// example of request that could be generated in Postman
{{baseUrl}}/someGetEndpoint?onlySelected=[1,2,3,4]
// Or in its percentile encoding version
{{baseUrl}}/someGetEndpoint?onlySelected=%5B1%2C2%2C3%2C4%5D
```

Thanks in advance

PS: Of course, I know we could do : 

```js
const Schema = require('openapi-enforcer').v3_0.Schema;
const myConfig /* = ... */;
Schema.defineDataTypeFormat('type', 'format', myConfig);
// ...
const Enforcer = require('openapi-enforcer-middleware')
const path = require('path')
const controllerDirectory = path.resolve(__dirname, 'controllers')
const pathToOpenApiDoc = path.resolve(__dirname, 'open-api-doc.yml')
// ....
const enforcer = Enforcer(pathToOpenApiDoc)
```

Just I don't prefer code that uses monkey patching at the fly ( except for tests where it is highly useful ;) )
